version: '3.8'

services:
  # MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # Backend Service (Node.js API)
  backend:
    build:
      context: ./backend # Path to the backend Dockerfile
    container_name: backend-api
    ports:
      - "5000:5000"
    environment:
      # Use the service name 'mongo' as the hostname
      MONGO_URI: mongodb://mongo:27017/inventory-management
      JWT_SECRET: your_super_secret_jwt_key_that_is_long_and_random
      PORT: 5000
    depends_on:
      - mongo # Ensures mongo starts before the backend
    restart: unless-stopped

  # Frontend Service (React + Vite served by Nginx)
  frontend:
    build:
      context: ./frontend # Path to the frontend Dockerfile
    container_name: frontend-client
    ports:
      # Map host port 80 to container port 80
      - "80:80"
    depends_on:
      - backend # Ensures backend starts before the frontend

# Define a named volume for persisting MongoDB data
volumes:
  mongo-data:
