services:
  backend:
    build:
      context: ./backend
    container_name: backend-api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://himanshukpal890:himanshu@cluster0.lj80wrp.mongodb.net/
      JWT_SECRET: himanshu
      PORT: 5000
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend 
    container_name: frontend-client
    ports:
      - "80:80"
    depends_on:
      - backend 
